### ISSUE TITLE
Incoming request body has been parsed as [object Object]

### ISSUE THREAD

**Issue by MysticEyeBlink** [mswjs/http-middleware#17]
Making POST request with JSON body, to mocked endpoint, produces body value as `[object Object]`.
The cause of this lays on using `express.json()` and then non-stringified JSON is changed to ArrayBuffer in `createMiddleware`.

Parsing text to JSON: 
https://github.com/mswjs/http-middleware/blob/ca849760dd3e32e990d33d66d393c101e5dc1f02/src/server.ts#L8

Encoding non-stringified JSON: https://github.com/mswjs/http-middleware/blob/ca849760dd3e32e990d33d66d393c101e5dc1f02/src/middleware.ts#L22

**Comment by kettanaito** [comment]
## Released: v0.5.1 🎉

This has been released in v0.5.1!

- 📄 [**Release notes**](https://github.com/mswjs/http-middleware/releases/tag/v0.5.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/http-middleware/v/0.5.1)

Make sure to always update to the latest version (`npm i @mswjs/http-middleware@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
