### ISSUE TITLE
GQL request hang with MSW 0.47.2

### ISSUE THREAD

**Issue by nnnnat** [mswjs/http-middleware#20]
Hey y'all, running into an issue when updating to MSW 0.47.2 where my GQL request never resolve. I'm able to log from the handler function so the request seems to make it but it never responses. Here is an [example repo](https://github.com/nnnnat/msw-middleware-example) with the issue recreated.

**Comment by stijnvanhulle** [comment]
I'm having the same issue :(

**Comment by AlanRad-QH** [comment]
REST API requests timeout too.

**Comment by kettanaito** [comment]
Hey, @nnnnat. Thanks for reporting this. 

It's strange, I thought this to be related to #18 but you are using the version of `http-middleware` with the fix. Someone has to look into what exactly is going on. I may look into this when I have time.

**Comment by mauron85** [comment]
REST API stopped working with 0.47.1. 0.47.0 still works

**Comment by robbtraister** [comment]
[this](https://github.com/mswjs/http-middleware/pull/21) looks to fix this on my local

**Comment by nnnnat** [comment]
Issue looks to be resolved using middleware v0.5.2 & msw 0.47.3.

Thanks @robbtraister & @kettanaito!
