### ISSUE TITLE
Q. Is there any roadmap for OpenAPI3 documentation?

### ISSUE THREAD

**Issue by SPONGE-JL** [mswjs/http-middleware#30]
Thanks for mswjs team and stand-alone service on this http-middleware application. It's amazing and easy usage to make stub application.

On the other hand, if the mocked API has been build up with implementation about real app, there would be needed to documation like [OAS3](https://spec.openapis.org/oas/v3.1.0). This has been spawn stand alone express in this module, so like `swagger-ui-express` and `swagger-jsdoc` would be used on diffent way maybe.

So is there any roadmap for OAS3?

Thanks for sharing your opinion.
Hope you well.

**Comment by kettanaito** [comment]
Hi! Thanks for your kind words. 

To clarify: do you suggest OA3 -> mock handlers or mock handlers -> OA3?

**Comment by kettanaito** [comment]
Okay, circling back to this with my best understanding of the question. 

## When will this package support OA3?

It won't. The purpose of this package is to translate MSW request handlers to Express handlers. Nothing else. 

## How do I add OAS to the mix then?

There is a library in the works that will do the "OAS -> request handlers" generation. It's mostly finished. I hope I will announce more news about it next year.
