### ISSUE TITLE
Compatability with MSW 2.0

### ISSUE THREAD

**Issue by tobeycodes** [mswjs/http-middleware#31]
It seems that `MockedRequest` is no longer exported from v2.0

**Comment by kettanaito** [comment]
Hi, @tobeycodes. No, it's not. You shouldn't be using `http-middleware` with MSW 2.0. This library supports a specific range of `msw`:

https://github.com/mswjs/http-middleware/blob/5dbd69d9eb737bfffc7f10b973a09bc8df4f55c9/package.json#L60

Pull requests are welcome to bump this package to support MSW 2.0!

**Comment by stijnvanhulle** [comment]
@kettanaito  @tobeycodes 

https://github.com/kubb-project/kubb/blob/9fb2494ce81e19e436a571357fcd26f1d7e972b7/examples/msw-v2/src/server.ts

Did some changes on my own project related to this, maybe this can become a PR to resolve the issue around `msw` 2.x.x :)

**Comment by kettanaito** [comment]
@stijnvanhulle, can you please open a pull request with that? I was just looking at the source code and that is _precisely_ what I would do. Your contribution would be appreciated!

**Comment by stijnvanhulle** [comment]
@kettanaito @tobeycodes 

Some building issues with the examples but tests and changes seem to work: https://github.com/mswjs/http-middleware/pull/32

**Comment by stijnvanhulle** [comment]
@tobeycodes https://github.com/mswjs/http-middleware/releases/tag/v0.9.0 has been released with support for MSW v2 :)
