### ISSUE TITLE
Question: Can you modify the mocked handlers per request

### ISSUE THREAD

**Issue by JoshAwaze** [mswjs/http-middleware#38]
Hi, before I start to use your library I was wondering if it supported the ability to change the underlying mocked handlers for each test.

E.g. 

```js
// some pseudo code

test('some happy path') {
page.goTo("/login"); // this should be mocked with default 200 response

}

test('some failure path') {

// override the response to simulate failure
  server.use(
    http.get('/login', () => {
      return new HttpResponse(null, { status: 500 })
    })
  )

}

```

**Comment by kettanaito** [comment]
Hi. Of course! 

This library takes your `handlers` array as an input:

https://github.com/mswjs/http-middleware/blob/dfd8c682696f47f3242c6f5a33ab9077a656c5b5/src/middleware.ts#L40

You can modify that array by prepending request handler overrides to that array. You don't get a more convenient API like `server.use()` though.
