### ISSUE TITLE
Graphql keeps pending 

### ISSUE THREAD

**Issue by viiiprock** [mswjs/http-middleware#4]
I tried to setup `http-middleware` with graphql as both `createServer` or `createMiddleware` as the document, but it only works with `rest` 
- graphql handlers is pending with createMiddleware (sometimes 404, I'm not sure) 🤔 
- 404 with createServer

I don't know if I'm missing something or it's an issue. Can I have an example with graphql? 

*Note*: I used `msw` for my nextjs, but since I had `/pages/[...slug].tsx`, it had issue with `graphql` endpoint, so I have to find another solution, seems `http-middleware` is what I'm looking for.

**Comment by viiiprock** [comment]
nvm, I don't much time, hardcode to skip catching `graphql` endpoint, use `msw` an removed `http-middleware` anyway.

**Comment by kettanaito** [comment]
Hey, @viiiprock.

You should be using MSW for API mocking. As the readme of this repository states, it's designed primarily for introspection and complex scenarios, like dockerized applications. Your case, based on the info you've provided, is neither and should use MSW directly. It can intercept and mock GraphQL operations without issues.

**Comment by viiiprock** [comment]
@kettanaito the truth is I still need a graphql mock server using MSW since my project is in NX mono-repo with separate admin site and web site. 
Hopefully this `html-middleware` can resolve this
Thanks for your answer!

**Comment by viiiprock** [comment]
@kettanaito here is my demo https://github.com/viiiprock/nx-msw
For the mock api I use `msw` and `html-middleware`. You can see at the web which consumes mockapi, it works well with rest API, but for graphql it's 404 on request `/graphql` endpoint.

**Comment by rsimp** [comment]
Is their any update on this? If the middleware doesn't respect graphql mockiing, then it should really be taken out of the docs, or a footnote saying it can only be used in a standalone server, which is not what express middleware implies

**Comment by andrzej-kodify** [comment]
See https://github.com/mswjs/msw-storybook-addon/issues/55#issuecomment-1079098538
For me the problem was lack of `body-parser` middleware on server, which in result made mocks skip GQL requests as they had no `body`
