### ISSUE TITLE
passthrough to external server

### ISSUE THREAD

**Issue by aleksanderd** [mswjs/http-middleware#40]
Hi!

I use standalone server mode since there is no express server(our API is PHP driven).

Is it possible passthrough all not mocked/handled routes to external/real api? Where to write the url, etc?

Thank you!

**Comment by kettanaito** [comment]
Hi, @aleksanderd. Thanks for raising this. 

The way this package is written is that it will invoke the `next()` middleware in line if there are no request handlers that matches the request:

https://github.com/mswjs/http-middleware/blob/dfd8c682696f47f3242c6f5a33ab9077a656c5b5/src/middleware.ts#L76

With that in mind, you can create your fallback logic and route the requests to any server you wish. Here's a rough example:

```js
import express from 'express'
import { createProxyMiddleware } from 'http-proxy-middleware'
import { createMiddleware } from '@mswjs/http-middleware'

const app = express()
const proxyServer = createProxyServer({
  host: 'https://you-server.com'
})

app.use(createMiddleware(...handlers))

app.use('*', createProxyMiddleware({
  target: 'https://yourdomain.com',
  changeOrigin: true
}))
```

This uses a third-party `http-proxy-middleware` package. This library has nothing to do with proxying requests.
