### ISSUE TITLE
Typescript issue with createServer

### ISSUE THREAD

**Issue by SalahAdDin** [mswjs/http-middleware#42]
The issue is easy:
![image](https://github.com/mswjs/http-middleware/assets/5034215/8e867b7a-d46b-4a23-8b6b-0d33e24a22ff)
Weirdly, cause handlers are well-typed:
![image](https://github.com/mswjs/http-middleware/assets/5034215/ac5ea1cb-7073-4645-be8a-49a99990d4f3)

What is going on here?

**Comment by nicolascvoodoo** [comment]
Hi @SalahAdDin, I get the same issue here. How did you resolve that, please?

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin, I get the same issue here. How did you resolve that, please?

As far as I remember I just refereshed the TS server.
