### ISSUE TITLE
Cannot set multiple cookies

### ISSUE THREAD

**Issue by ernestostifano** [mswjs/http-middleware#44]
Hello!

I've been trying many different ways to set multiple cookies on my responses with no luck.

Some of the tested approaches work on the browser (using`msw` directly), but none work while using the `http-middleware`.

For example, the following works perfectly using `msw` on the browser, but not using the `http-middleware`:

```js
    return HttpResponse.json(
        body,
        {
            headers: [
                [
                    'Set-Cookie',
                    `${COOKIE_NAMES.ACCESS_TOKEN}=${session.accessToken.value}; Path=/; Max-Age=${TOKENS.ACCESS_TOKEN_MAX_AGE};`
                ],
                [
                    'Set-Cookie',
                    `${COOKIE_NAMES.REFRESH_TOKEN}=${session.refreshToken.value}; Path=/; Max-Age=${TOKENS.REFRESH_TOKEN_EXP_MAX_AGE};`
                ]
            ]
        }
    );
```

Using the `http-middleware`, only the last cookie is sent from express.

Other approaches I tried involved using:
- `Headers` constructor (using `append`).
- `headers-polyfill`.
- Different overloads of `HttpResponse.json`.
- Native `Response.json`.

I have the following configuration before the `htttp-middleware`:

```js
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', req.get('origin') || '*');

    res.header('Access-Control-Allow-Credentials', 'true');

    res.header('Access-Control-Allow-Methods', '*');

    res.header(
        'Access-Control-Allow-Headers',
        'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers'
    );

    if (req.method === 'OPTIONS') {
        return res.sendStatus(200);
    }

    return next();
});

app.use(express.json());
```

Potentially related issues:
- https://github.com/mswjs/msw/issues/640
- https://github.com/mswjs/headers-polyfill/issues/29

**Comment by kettanaito** [comment]
Hi, @ernestostifano! Thanks for letting me know. The fix is merged, the release will happen later tonight.
