### ISSUE TITLE
Discussion : mswjs/http-middleware to serve mock data for visual regression tests

### ISSUE THREAD

**Issue by KishaniKandasamy** [mswjs/http-middleware#6]
Hi everyone , Is there any getting  started  guide to mock data for visual regression tests using mswjs/http-middleware?

**Comment by kettanaito** [comment]
Hey, @KishaniKandasamy.

Frankly, I think you'll get far better results by using [MSW](https://github.com/mswjs/msw) directly. Using `@mswjs/http-middleware` implies running a standalone mocking server. Apart from the runtime cost of that, you'd have to stir your entire application to communicate with that said server. That kind of deviation means you're no longer testing the same app as your users see. 

With MSW, however, you enable request interception on the network level and can keep requesting the same resources from the production endpoints in your regression tests. Obviously, their responses will be mocked according to your requirements. We've got a good [Getting started tutorial](https://mswjs.io/docs/getting-started/install) you can follow to get an idea what the integration of MSW would look like for your tests.
